apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: lizaavsyannik/online_inference:v5
      name: online-inference
      ports:
        - containerPort: 8000
