apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: lizaavsyannik/online_inference:v6
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "1Gi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 5
